module.exports={
    COMMUNITY_CHAT:"COMMUNITY_CHAT"
,    MESSAGE_SENT:"MESSAGE_SENT",
    MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
    USER_CONNECTED:"USER_CONNECTED",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    LOGOUT:" LOGOUT"


}